# Generated by Django 4.0 on 2022-01-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Others')], max_length=1)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('pincode', models.CharField(max_length=4)),
                ('phone', models.BigIntegerField(max_length=10)),
            ],
        ),
    ]
