# Generated by Django 4.0 on 2022-01-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
